### ISSUE TITLE
Better message

### ISSUE THREAD

**Issue by bahmutov** [bahmutov/next-ver#5]
Instead of just saying `next version should be 1.22.0` it should say
`next version should be 1.22.0 (1 feature, 2 fixes)` for example

**Comment by lirantal** [comment]
@bahmutov supporting a silent mode as well where you just output the new version number so it can be used for other means in a CI (git tags etc)

**Comment by bahmutov** [comment]
Yeah, good ideas, would love if you could submit pull request and we would merge it in

**Comment by lirantal** [comment]
Great, I'll push it
